name: PUSH Workflow

on:
  push:
    branches:
      - master

jobs:
  app-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql-database:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'
          extensions: mbstring, xml, bcmath, sqlite3, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Copy .env from secrets
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_ENV=${{ env.APP_ENV }}" >> .env
          echo "APP_DEBUG=${{ env.APP_DEBUG }}" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "SESSION_DRIVER=${{ env.SESSION_DRIVER }}" >> .env
          echo "DB_HOST=127.0.0.1" >> .env  # Use localhost for the GitHub Actions service
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test_database" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      
      - name: Ensure bootstrap/cache directory exists
        run: |
          mkdir -p bootstrap/cache
          chmod -R 775 bootstrap/cache

      - name: Run migrations
        run: php artisan migrate

      - name: Run tests
        run: php artisan test
